(function(){
'use strict';
const $=id=>document.getElementById(id);
const STEPS=['Experiment','Calibration','Control','Candidate','Motion','Review','Seal'];
const P1='physical_garment_p1';
let stream=null,recorder=null,chunks=[],arm='control',frozen=null,sealed=false,runtimeConnected=false,p1Binding=null;
const captures={control:{stills:[],videos:[]},candidate:{stills:[],videos:[]}};
const calibrationSources={pre:null,post:null};
function now(){return new Date().toISOString()}
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object'){const out={};Object.keys(v).sort().forEach(k=>out[k]=stable(v[k]));return out;}return v}
function canonical(v){return JSON.stringify(stable(v))}
function cond(){return [+$('distance').value,+$('yaw').value,+$('pitch').value,$('pose').value,$('lightingId').value].join('|')}
function hex(buf){return crypto.subtle.digest('SHA-256',buf).then(d=>[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join(''))}
function isP1(){return $('evidenceClass').value===P1}
function renderSteps(active=0){$('sopStrip').innerHTML=STEPS.map((s,i)=>'<div class="sop-step '+(i<active?'done ':i===active?'active':'')+'">'+(i+1)+' · '+s.toUpperCase()+'</div>').join('')}
function count(){for(const a of ['control','candidate'])$(a+'Count').textContent=captures[a].stills.length+' stills · '+captures[a].videos.length+' videos'}
function anyCapture(){return ['control','candidate'].some(a=>captures[a].stills.length||captures[a].videos.length)}
function calibrationGateText(){
 if(!isP1())return $('calibrationPass').checked?'ACKNOWLEDGED':'Pending';
 const pre=calibrationSources.pre?.accepted===true,post=calibrationSources.post?.accepted===true;
 if(pre&&post)return'PRE PASS · POST PASS';if(pre)return'PRE PASS · POST PENDING';return'PRE PENDING';
}
function refreshCalibrationGate(){$('calibrationGate').querySelector('span').textContent=calibrationGateText()}
function manifest(){
 const pre=calibrationSources.pre;
 return {schema_version:'1.0',session_id:'RAC-CAP-'+Date.now(),experiment_id:$('experimentId').value,hypothesis_id:$('hypothesisId').value,protocol_version:$('protocolVersion').value,evidence_class:$('evidenceClass').value,trial_id:isP1()?p1Binding?.trial_id:null,p1_schedule:isP1()?p1Binding:null,generation:{artifact_id:$('generationId').value,sha256:$('generationSha').value.toLowerCase()},candidate:{artifact_id:$('candidateId').value,sha256:$('candidateSha').value.toLowerCase()},control:{artifact_id:$('controlId').value},actor_id:$('actorId').value,camera_id:$('cameraId').value,lighting_id:$('lightingId').value,lighting_variant:$('lightingVariant').value||null,distance_m:+$('distance').value,yaw_deg:+$('yaw').value,pitch_deg:+$('pitch').value,pose:$('pose').value,calibration_profile_id:isP1()?pre?.profile_id:null,calibration_profile_sha256:isP1()?pre?.source_sha256:null,created_at:now(),capture_blinding:'outcomes_hidden_until_capture_pair_complete',statistical_unit:'garment_x_actor_x_session',frames_are_nested:true}
}
function p1InputsLocked(locked){['distance','yaw','pitch','pose','trialId','lightingVariant'].forEach(id=>$(id).disabled=locked)}
function syncEvidenceMode(){
 const physical=isP1();$('p1CalibrationTools').style.display=physical?'block':'none';$('prototypeCalibrationLabel').style.display=physical?'none':'flex';$('loadNextTrialBtn').disabled=!physical||!runtimeConnected||!!frozen;
 if(!physical&&!frozen){p1Binding=null;$('trialId').value='';$('lightingVariant').value='';$('p1ScheduleStatus').textContent='Select PHYSICAL GARMENT / P1 to bind a frozen trial.';$('p1ArmOrder').textContent='Arm order not loaded.';p1InputsLocked(false)}
 refreshCalibrationGate()
}
async function loadNextP1Trial(){
 if(!isP1())return alert('Select PHYSICAL GARMENT / P1 first.');if(!runtimeConnected)return alert('The local Research Workbench runtime is required for frozen P1 schedule binding.');
 const res=await fetch('/api/runtime/p1/schedule?trial_store='+encodeURIComponent('research/p1/trials.jsonl'),{cache:'no-store'});const p=await res.json();if(!res.ok)throw new Error(p.error||('HTTP '+res.status));
 if(!p.next_trial){$('p1ScheduleStatus').textContent='P1 SCHEDULE COMPLETE · '+p.completed_trials+'/'+p.planned_trials;return}
 const e=p.next_trial;p1Binding={contract_id:p.contract_id,schedule_sha256:p.schedule_sha256,trial_id:e.trial_id,execution_position:e.execution_position,cell_id:e.cell_id,repetition:e.repetition,first_arm:e.first_arm,arms:e.arms,distance_m:e.distance_m,yaw_deg:e.yaw_deg,pitch_deg:e.pitch_deg,lighting_variant:e.lighting_variant,pose:e.pose};
 $('trialId').value=e.trial_id;$('lightingVariant').value=e.lighting_variant;$('distance').value=e.distance_m;$('yaw').value=e.yaw_deg;$('pitch').value=e.pitch_deg;$('pose').value=e.pose;p1InputsLocked(true);switchArm(e.first_arm,true);
 $('p1ScheduleStatus').textContent='BOUND · '+e.trial_id+' · position '+e.execution_position+'/'+p.planned_trials+' · '+p.completed_trials+' completed';$('p1ArmOrder').textContent='FROZEN ARM ORDER · '+e.arms.map(x=>x.toUpperCase()).join(' → ')
}
function rad(x){return x*Math.PI/180}
function deltaE2000(lab1,lab2){
 const [L1,a1,b1]=lab1.map(Number),[L2,a2,b2]=lab2.map(Number),C1=Math.hypot(a1,b1),C2=Math.hypot(a2,b2),Cbar=(C1+C2)/2,Cbar7=Cbar**7,G=Cbar>0?.5*(1-Math.sqrt(Cbar7/(Cbar7+25**7))):0,a1p=(1+G)*a1,a2p=(1+G)*a2,C1p=Math.hypot(a1p,b1),C2p=Math.hypot(a2p,b2);
 const hp=(a,b)=>{if(a===0&&b===0)return 0;let h=Math.atan2(b,a)*180/Math.PI;return h<0?h+360:h};const h1p=hp(a1p,b1),h2p=hp(a2p,b2),dLp=L2-L1,dCp=C2p-C1p;let dhp=0;if(C1p*C2p!==0){dhp=h2p-h1p;if(dhp>180)dhp-=360;else if(dhp<-180)dhp+=360}const dHp=2*Math.sqrt(C1p*C2p)*Math.sin(rad(dhp)/2),Lpbar=(L1+L2)/2,Cpbar=(C1p+C2p)/2;let hpbar;if(C1p*C2p===0)hpbar=h1p+h2p;else{const dh=Math.abs(h1p-h2p);if(dh<=180)hpbar=(h1p+h2p)/2;else if(h1p+h2p<360)hpbar=(h1p+h2p+360)/2;else hpbar=(h1p+h2p-360)/2}const T=1-.17*Math.cos(rad(hpbar-30))+.24*Math.cos(rad(2*hpbar))+.32*Math.cos(rad(3*hpbar+6))-.20*Math.cos(rad(4*hpbar-63)),dtheta=30*Math.exp(-(((hpbar-275)/25)**2)),RC=Cpbar>0?2*Math.sqrt(Cpbar**7/(Cpbar**7+25**7)):0,SL=1+.015*(Lpbar-50)**2/Math.sqrt(20+(Lpbar-50)**2),SC=1+.045*Cpbar,SH=1+.015*Cpbar*T,RT=-Math.sin(rad(2*dtheta))*RC;return Math.sqrt((dLp/SL)**2+(dCp/SC)**2+(dHp/SH)**2+RT*(dCp/SC)*(dHp/SH))
}
function previewCalibration(payload,phase,sourceSha){
 if(!payload||typeof payload!=='object')throw new Error('Calibration profile must be a JSON object.');const patches=Array.isArray(payload.patches)?payload.patches:[],scales=Array.isArray(payload.scales)?payload.scales:[],regs=Array.isArray(payload.registrations)?payload.registrations:[];
 if(patches.length!==48)throw new Error('P1 calibration requires exactly 48 measured patches.');if(scales.length<2)throw new Error('P1 calibration requires at least two scale measurements.');const fids=[...new Set(regs.map(r=>r.mark_id))].sort();if(regs.length!==4||fids.join('|')!==['FID-BL','FID-BR','FID-TL','FID-TR'].join('|'))throw new Error('P1 calibration requires exactly the four frozen fiducials.');if(payload.camera_id!==$('cameraId').value)throw new Error('Calibration camera_id must match the session camera.');if(payload.lighting_id!==$('lightingId').value)throw new Error('Calibration lighting_id must match the session lighting.');
 const des=patches.map(p=>deltaE2000(p.reference_lab,p.measured_lab));if(des.some(v=>!Number.isFinite(v)))throw new Error('Calibration patch values are invalid.');const meanDE=des.reduce((a,b)=>a+b,0)/des.length,pxcm=scales.map(s=>Number(s.measured_px)/Number(s.nominal_cm));if(pxcm.some(v=>!Number.isFinite(v)||v<=0))throw new Error('Scale measurements are invalid.');const meanPx=pxcm.reduce((a,b)=>a+b,0)/pxcm.length,scaleErrors=pxcm.map(v=>(v-meanPx)/meanPx*100),maxScale=Math.max(...scaleErrors.map(Math.abs)),regErrors=regs.map(r=>Math.hypot(Number(r.measured_xy_mm[0])-Number(r.nominal_xy_mm[0]),Number(r.measured_xy_mm[1])-Number(r.nominal_xy_mm[1]))),maxReg=Math.max(...regErrors);
 const failures=[];if(meanDE>6)failures.push('mean ΔE2000 '+meanDE.toFixed(3)+' > 6.0');if(maxScale>2)failures.push('scale error '+maxScale.toFixed(3)+'% > 2.0%');if(maxReg>3)failures.push('registration error '+maxReg.toFixed(3)+' mm > 3.0 mm');if(!payload.profile_id)failures.push('profile_id missing');if(!payload.created_utc)failures.push('created_utc missing');
 return{phase,profile_id:String(payload.profile_id||''),camera_id:String(payload.camera_id||''),lighting_id:String(payload.lighting_id||''),created_utc:String(payload.created_utc||''),source_sha256:sourceSha,accepted:failures.length===0,failures,summary:{mean_delta_e:meanDE,max_scale_error_pct:maxScale,max_registration_error_mm:maxReg},measurement_completeness:{patches:48,scales:scales.length,fiducials:fids}}
}
async function validateCalibration(phase){
 const input=$(phase==='pre'?'preCalibrationFile':'postCalibrationFile'),status=$(phase==='pre'?'preCalibrationStatus':'postCalibrationStatus'),file=input.files&&input.files[0];if(!file)return alert('Choose a measured calibration profile JSON file.');if(phase==='post'&&!captures.control.stills.length&&!captures.candidate.stills.length)return alert('Post-capture calibration belongs after garment capture.');
 try{const text=await file.text(),payload=JSON.parse(text),sha=await hex(new TextEncoder().encode(text)),receipt=previewCalibration(payload,phase,sha);if(phase==='post'&&calibrationSources.pre?.created_utc&&Date.parse(receipt.created_utc)<Date.parse(calibrationSources.pre.created_utc))throw new Error('Post-capture calibration timestamp precedes pre-capture calibration.');calibrationSources[phase]={source_text:text,source_sha256:sha,...receipt};status.textContent=(receipt.accepted?'PASS · ':'FAIL · ')+receipt.profile_id+' · mean ΔE '+receipt.summary.mean_delta_e.toFixed(2)+' · scale '+receipt.summary.max_scale_error_pct.toFixed(2)+'% · reg '+receipt.summary.max_registration_error_mm.toFixed(2)+' mm'+(receipt.failures.length?' · '+receipt.failures.join('; '):'');status.className='analysis '+(receipt.accepted?'':'error');refreshCalibrationGate()}catch(e){calibrationSources[phase]=null;status.textContent='FAIL · '+e.message;status.className='analysis error';refreshCalibrationGate()}
}
async function freeze(){
 const physical=isP1();if(physical){if(!runtimeConnected)return alert('Physical P1 requires the connected Research Workbench runtime.');if(!p1Binding)return alert('Load the next frozen P1 trial before freezing the session.');if(calibrationSources.pre?.accepted!==true)return alert('Accepted measured pre-capture calibration is required before physical P1 capture.');}
 const m=manifest();if(!m.experiment_id||!m.actor_id||!m.camera_id)return alert('Experiment, actor, and camera IDs are required.');if(physical&&(!m.candidate.artifact_id||!m.generation.artifact_id))return alert('Physical P1 requires frozen candidate and generation artifact IDs.');if(physical&&(!/^[0-9a-f]{64}$/.test(m.candidate.sha256)||!/^[0-9a-f]{64}$/.test(m.generation.sha256)))return alert('Physical P1 requires frozen 64-hex candidate and generation SHA-256 values.');if(!physical&&m.candidate.sha256&&!/^[0-9a-f]{64}$/.test(m.candidate.sha256))return alert('Candidate SHA-256 must be 64 hex characters or blank for a prototype.');if(!physical&&m.generation.sha256&&!/^[0-9a-f]{64}$/.test(m.generation.sha256))return alert('Generation SHA-256 must be 64 hex characters or blank for a prototype.');
 const bytes=new TextEncoder().encode(canonical(m));m.freeze_sha256=await hex(bytes);frozen=m;['experimentId','hypothesisId','protocolVersion','evidenceClass','generationId','generationSha','candidateId','candidateSha','controlId','actorId','cameraId','lightingId','distance','yaw','pitch','pose','trialId','lightingVariant'].forEach(id=>$(id).disabled=true);$('loadNextTrialBtn').disabled=true;$('freezeBtn').disabled=true;$('stillBtn').disabled=!stream;$('recordBtn').disabled=!stream;$('instrumentStatus').textContent='FROZEN · '+m.freeze_sha256.slice(0,16)+'…';$('conditionBanner').textContent=arm.toUpperCase()+' · '+cond();renderSteps(1)
}
async function camera(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('camera').srcObject=stream;$('cameraBtn').textContent='Camera Ready';$('cameraBtn').disabled=true;$('stillBtn').disabled=!frozen;$('recordBtn').disabled=!frozen;$('capturePrompt').textContent='FRAMING GUIDE · OUTCOMES BLINDED'}catch(e){$('instrumentStatus').textContent='CAMERA ERROR · '+e.message}}
async function still(){if(!frozen||sealed)return;const v=$('camera'),c=document.createElement('canvas');c.width=v.videoWidth||1280;c.height=v.videoHeight||720;c.getContext('2d').drawImage(v,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.95));const bytes=await blob.arrayBuffer(),rec={id:arm+'-still-'+(captures[arm].stills.length+1),arm,type:'still',condition:cond(),timestamp:now(),sha256:await hex(bytes),blob};captures[arm].stills.push(rec);ledger(rec);count();renderSteps(arm==='control'?2:3)}
function startRecord(){if(!stream||!frozen||sealed)return;chunks=[];recorder=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm'});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=finishRecord;recorder.start(250);$('recordBtn').disabled=true;$('stopBtn').disabled=false;$('capturePrompt').textContent='RECORDING '+arm.toUpperCase()+' · '+$('pose').value.toUpperCase()}
async function finishRecord(){const blob=new Blob(chunks,{type:recorder.mimeType});const bytes=await blob.arrayBuffer(),rec={id:arm+'-video-'+(captures[arm].videos.length+1),arm,type:'motion',condition:cond(),timestamp:now(),sha256:await hex(bytes),blob};captures[arm].videos.push(rec);ledger(rec);count();$('recordBtn').disabled=false;$('stopBtn').disabled=true;$('capturePrompt').textContent='FRAMING GUIDE · OUTCOMES BLINDED';renderSteps(4)}
function stopRecord(){if(recorder&&recorder.state!=='inactive')recorder.stop()}
function ledger(r){const tr=document.createElement('tr');tr.innerHTML='<td>'+r.timestamp+'</td><td>'+r.arm+'</td><td>'+r.type+'</td><td>'+r.condition+'</td><td>'+r.sha256+'</td>';$('ledger').appendChild(tr)}
function switchArm(a,force=false){if(isP1()&&p1Binding&&!anyCapture()&&!force&&a!==p1Binding.first_arm)return alert('Frozen P1 arm order requires '+p1Binding.first_arm.toUpperCase()+' first.');arm=a;document.querySelectorAll('.arm').forEach(b=>b.classList.toggle('active',b.dataset.arm===a));$('conditionBanner').textContent=a.toUpperCase()+' · '+cond()}
function review(){const same=captures.control.stills.length>0&&captures.candidate.stills.length>0;if(!same)return alert('At least one still is required for both control and candidate before review.');$('analyzeBtn').disabled=false;$('exportBtn').disabled=false;$('sealBtn').disabled=false;if(isP1())$('validatePostCalibrationBtn').disabled=false;$('analysisStatus').textContent='CAPTURE PAIR VALID · analysis may now run without changing capture.';renderSteps(5)}
function analyze(){let mm;try{mm=JSON.parse($('modelManifest').value)}catch(e){return alert('Model manifest JSON is invalid.')}if(!Array.isArray(mm.models)||typeof mm.thresholds!=='object')return alert('Frozen model manifest requires models[] and thresholds{}.');$('modelManifest').disabled=true;$('analyzeBtn').disabled=true;const payload={schema_version:'1.0',status:'analysis_pending_local_runner',session_freeze_sha256:frozen.freeze_sha256,models:mm.models,thresholds:mm.thresholds,preprocessing:mm.preprocessing||{},motion_sampling:mm.motion_sampling||null,identity_mode:mm.identity_mode||'disabled',note:'Execute through the connected RAC Research Workbench. Browser does not fabricate inference.'};$('analysisStatus').textContent='ANALYSIS CONTRACT FROZEN · '+mm.models.length+' models · ready for Research Workbench.';frozen.analysis_contract=payload}
function buildSession(){
 const physical=frozen?.evidence_class===P1,calibrationPass=physical?(calibrationSources.pre?.accepted===true&&calibrationSources.post?.accepted===true):$('calibrationPass').checked,files=[],session={...frozen,calibration_pass:calibrationPass,sealed,captures:{control:{stills:[],videos:[]},candidate:{stills:[],videos:[]}}};
 if(physical)session.calibration={pre:{source_text:calibrationSources.pre?.source_text||'',source_sha256:calibrationSources.pre?.source_sha256||''},post:{source_text:calibrationSources.post?.source_text||'',source_sha256:calibrationSources.post?.source_sha256||''}};
 for(const a of ['control','candidate'])for(const t of ['stills','videos'])for(const r of captures[a][t]){const ext=r.type==='still'?'jpg':'webm',name=a+'/'+r.id+'.'+ext;files.push({name,blob:r.blob});session.captures[a][t].push({...r,blob:undefined,path:name})}return{session,files}
}
async function exportBundle(){const {session,files}=buildSession(),data=new Blob([JSON.stringify(session,null,2)],{type:'application/json'});download(data,(frozen.session_id||'rac-capture')+'-session.json');for(const f of files)download(f.blob,(frozen.session_id||'rac-capture')+'-'+f.name.replaceAll('/','-'))}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function runtimePath(path){return String(path).split('/').map(encodeURIComponent).join('/')}
async function runtimeUpload(rel,blob){const res=await fetch('/api/runtime/workspace/'+runtimePath(rel),{method:'PUT',body:blob});const payload=await res.json();if(!res.ok)throw new Error(payload.error||('HTTP '+res.status));return payload}
async function checkRuntime(){try{const res=await fetch('/api/runtime/status',{cache:'no-store'});if(!res.ok)throw new Error('not connected');const p=await res.json();runtimeConnected=p.connected===true}catch(_){runtimeConnected=false}const s=$('runtimeStatus');if(s)s.textContent=runtimeConnected?'RESEARCH RUNTIME · CONNECTED':'RESEARCH RUNTIME · STATIC / READ-ONLY';if($('runtimeStageBtn'))$('runtimeStageBtn').disabled=!(runtimeConnected&&sealed);syncEvidenceMode()}
async function stageSessionToRuntime(){if(!runtimeConnected)throw new Error('Research Workbench runtime is not connected.');if(!sealed)throw new Error('Seal the session before staging.');const {session,files}=buildSession(),base='sessions/'+frozen.session_id;$('sealStatus').textContent='STAGING SEALED SESSION · 0/'+(files.length+1);let n=0;for(const f of files){await runtimeUpload(base+'/'+f.name,f.blob);n++;$('sealStatus').textContent='STAGING SEALED SESSION · '+n+'/'+(files.length+1)}const sessionRel=base+'/'+frozen.session_id+'-session.json';await runtimeUpload(sessionRel,new Blob([JSON.stringify(session,null,2)],{type:'application/json'}));const state={session:sessionRel,inference:base+'/inference.json',output_dir:base+'/p1-output',trial_store:'research/p1/trials.jsonl'};try{localStorage.setItem('racLastStagedSession',JSON.stringify(state))}catch(_){}$('sealStatus').textContent='SEALED + STAGED · '+sessionRel;$('runtimeStageBtn').disabled=false;return state}
async function seal(){const physical=frozen?.evidence_class===P1;if(physical&&calibrationSources.post?.accepted!==true)return alert('Accepted measured post-capture calibration is required before sealing physical P1.');if(!physical&&!$('calibrationPass').checked)return alert('Calibration acknowledgment is required before sealing this prototype session.');if(!captures.control.stills.length||!captures.candidate.stills.length)return alert('Matched capture pair incomplete.');if(!frozen.analysis_contract)return alert('Freeze the ensemble analysis contract before sealing the session.');sealed=true;$('sealBtn').disabled=true;$('stillBtn').disabled=true;$('recordBtn').disabled=true;$('reviewBtn').disabled=true;$('sealStatus').textContent='SEALED · IMMUTABLE CAPTURE SESSION';renderSteps(6);if(runtimeConnected){try{await stageSessionToRuntime()}catch(e){$('sealStatus').textContent='SEALED · RUNTIME STAGING FAILED · '+e.message;await exportBundle()}}else await exportBundle()}
function preset(name){const sets={surrogate:{models:['yolov8n','fasterrcnn_mobilenet_v3_320','detr_resnet50','ssdlite320_mobilenet_v3','retinanet_resnet50_fpn_v2','fcos_resnet50_fpn']},heldout:{models:['fasterrcnn_resnet50_fpn_v2','maskrcnn_resnet50_fpn_v2']}};if(name==='custom')return;const models=sets[name].models,thresholds=Object.fromEntries(models.map(m=>[m,0.5]));$('modelManifest').value=JSON.stringify({models,thresholds,preprocessing:{source:'frozen model manifests'},motion_sampling:{fps:2.0,max_frames:120,aggregation:'sequence_fraction',sequence_detection_threshold:0.5},identity_mode:'disabled'},null,2)}
function init(){renderSteps(0);count();syncEvidenceMode();$('evidenceClass').onchange=syncEvidenceMode;$('ensemblePreset').onchange=()=>preset($('ensemblePreset').value);$('loadNextTrialBtn').onclick=async()=>{try{await loadNextP1Trial()}catch(e){$('p1ScheduleStatus').textContent='SCHEDULE REFUSED · '+e.message}};$('validatePreCalibrationBtn').onclick=()=>validateCalibration('pre');$('validatePostCalibrationBtn').onclick=()=>validateCalibration('post');$('freezeBtn').onclick=freeze;$('cameraBtn').onclick=camera;$('stillBtn').onclick=still;$('recordBtn').onclick=startRecord;$('stopBtn').onclick=stopRecord;$('reviewBtn').onclick=review;$('analyzeBtn').onclick=analyze;$('exportBtn').onclick=exportBundle;$('sealBtn').onclick=seal;$('runtimeStageBtn').onclick=async()=>{try{await stageSessionToRuntime()}catch(e){$('sealStatus').textContent='RUNTIME STAGING FAILED · '+e.message}};document.querySelectorAll('.arm').forEach(b=>b.onclick=()=>switchArm(b.dataset.arm));$('calibrationPass').onchange=refreshCalibrationGate;checkRuntime();setInterval(checkRuntime,15000)}
window.RACCaptureLab={manifest,freeze,review,analyze,seal,loadNextP1Trial,validateCalibration,stageSessionToRuntime,getState:()=>({frozen,sealed,captures,runtimeConnected,p1Binding,calibrationSources})};window.addEventListener('DOMContentLoaded',init)
})();