const RACStudio=(()=>{
  const W=1122,H=1402;
  const N={
    hoodie:'MACHINE STATIC HOODIE',
    hat:'SIGNAL SHADOW HAT',
    beanie:'GHOST HOUND BEANIE',
    cargo:'BROKEN HUMAN CARGO PANTS',
    mask:'MACHINE STATIC MASK',
    shirt:'ERROR GARDEN SHIRT'
  };
  const F={hoodie:'machine_static',hat:'signal_shadow',beanie:'ghost_hound',cargo:'broken_human',mask:'machine_static',shirt:'error_garden'};
  const S={
    signal_shadow:['SIGNAL LAYERING','SUBTLE HIGH-CONTRAST CUES','INTERFERENCE GEOMETRY','FRAGMENTED VISUAL LANGUAGE','WEARABLE COMPLEXITY','HIDDEN ANIMAL FORMS'],
    machine_static:['MICRO-BLOCK DISRUPTION','INTERFERENCE TEXTURES','DIRECTIONAL GRAIN LAYERS','TONAL SIGNAL OVERLAYS','HIGH CONTRAST + LOW VISIBILITY','WEARABLE CAMOUFLAGE'],
    ghost_hound:['FRAGMENTED CANINE CUES','SILHOUETTE DISRUPTION','COMPETING VISUAL SIGNALS','HIGH CONTRAST + DIRECTIONAL NOISE','WEARABLE CAMOUFLAGE'],
    broken_human:['FRAGMENTED HUMAN CUES','DISPLACED ANATOMY','HIGH CONTRAST + DIRECTIONAL BREAKS','UTILITY DRIVEN CONSTRUCTION','ARTICULATED FORM FOR MOVEMENT','WEARABLE CAMOUFLAGE'],
    error_garden:['ORGANIC FLORAL FORMS','PIXEL CLUSTERS & DIGITAL ARTIFACTS','DISGUISED ANIMAL FRAGMENTS','FLUID NON-REPETITIVE COMPOSITION','HIGH CONTRAST + NATURAL TENSION','WEARABLE CAMOUFLAGE']
  };
  const T={hoodie:'',hat:'',beanie:'',cargo:'',mask:'',shirt:''};
  const DESC={signal_shadow:'',machine_static:'',ghost_hound:'',broken_human:'',error_garden:''};
  const VERBS={signal_shadow:[],machine_static:[],ghost_hound:[],broken_human:[],error_garden:[]};
  const FAMILY_TITLE={signal_shadow:'SIGNAL SHADOW',machine_static:'MACHINE STATIC',ghost_hound:'GHOST HOUND',broken_human:'BROKEN HUMAN',error_garden:'ERROR GARDEN'};

  let tile=null,manifest=null,mode='generate',variationPreset='original';
  let renderRevision=0,renderFrame=0;
  const selectedMotifs=new Set();
  const showcaseImage=new Image();
  let showcaseReady=false;
  const $=id=>document.getElementById(id);
  function state(){
    const product=$('productType').value;
    let family=$('designFamily').value;
    if(family==='auto')family=F[product];
    return {product,family,brand:($('brandName').value||'RUTHLESS').trim().toUpperCase(),productName:($('productName').value||N[product]).trim().toUpperCase(),collection:($('collectionName').value||'URBAN WILDERNESS').trim().toUpperCase(),seed:+$('studioSeed').value,scale:+$('studioScale').value,density:+$('studioDensity').value,distress:+$('studioDistress').value,featureMotifs:[...selectedMotifs],useShowcaseSource:Boolean($('useShowcaseSource')&&$('useShowcaseSource').checked),showcaseRegion:$('showcaseRegion')?$('showcaseRegion').value:'motifs',showcaseStrength:$('showcaseStrength')?+$('showcaseStrength').value:28,variationPreset};
  }
  function defaults(force=false){const p=$('productType').value;if(force||!$('productName').dataset.edited)$('productName').value=N[p];const f=$('designFamily').value==='auto'?F[p]:$('designFamily').value;$('resolvedFamily').textContent=f.replaceAll('_',' ').toUpperCase();}
  function sync(id){const e=$(id+'Value');if(e)e.textContent=$(id).value;}
  function showcaseCrop(region,img){const w=img.naturalWidth||img.width,h=img.naturalHeight||img.height;if(region==='motifs')return{x:0,y:h*.055,w,h:h*.19};if(region==='families')return{x:0,y:h*.215,w,h:h*.235};if(region==='tiles')return{x:0,y:h*.44,w,h:h*.18};return{x:0,y:0,w,h};}
  function applyShowcaseSource(ctx,size,s){if(!s.useShowcaseSource||!showcaseReady)return;const crop=showcaseCrop(s.showcaseRegion,showcaseImage);const strength=Math.max(.05,Math.min(.7,s.showcaseStrength/100));const block=document.createElement('canvas');block.width=Math.max(64,Math.round(size/3));block.height=block.width;const bx=block.getContext('2d');bx.imageSmoothingEnabled=false;bx.drawImage(showcaseImage,crop.x,crop.y,crop.w,crop.h,0,0,block.width,block.height);ctx.save();ctx.globalAlpha=strength;ctx.globalCompositeOperation='screen';ctx.imageSmoothingEnabled=false;const step=Math.max(96,Math.round(size*.34));for(let y=-step;y<size+step;y+=step)for(let x=-step;x<size+step;x+=step){ctx.save();ctx.translate(x+step/2,y+step/2);ctx.rotate(((x+y+s.seed)%5-2)*.035);ctx.drawImage(block,-step/2,-step/2,step,step);ctx.restore();}ctx.restore();}
  function makeTile(size,s=state()){const c=document.createElement('canvas');c.width=c.height=size;const x=c.getContext('2d');const effectiveScale=s.variationPreset==='scale_plus'?Math.min(100,s.scale+24):s.scale;const p={patternType:s.family,patternScale:effectiveScale,colorVariance:s.density,edgeIntensity:s.distress,symmetry:0,seed:s.seed,featureMotifs:s.featureMotifs};const pal=colorPalettes[s.family==='error_garden'?'error_garden':'rac_reference'];const r=seededRandom(s.seed),g=patternGenerators[s.family];if(!g)throw new Error('Missing pattern family: '+s.family);g(x,size,p,pal,r);applyShowcaseSource(x,size,s);if(s.variationPreset!=='original'&&s.variationPreset!=='scale_plus'){const copy=document.createElement('canvas');copy.width=copy.height=size;copy.getContext('2d').drawImage(c,0,0);x.clearRect(0,0,size,size);x.save();if(s.variationPreset==='high_contrast')x.filter='contrast(175%) saturate(115%)';if(s.variationPreset==='desaturated')x.filter='grayscale(100%) contrast(125%)';if(s.variationPreset==='alt_palette')x.filter='hue-rotate(135deg) saturate(140%) contrast(115%)';x.drawImage(copy,0,0);x.restore();}return c;}
  function rr(c,x,y,w,h,r){r=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath();}
  function fill(c,t,x,y,w,h,sz){for(let yy=y;yy<y+h;yy+=sz)for(let xx=x;xx<x+w;xx+=sz)c.drawImage(t,xx,yy,sz,sz);}
  function clip(c,p,t,b,sz){c.save();c.clip(p);fill(c,t,b.x,b.y,b.w,b.h,sz);c.restore();}
  function sh(c,x,y,rx,ry){c.save();c.globalAlpha=.12;c.fillStyle='#000';c.filter='blur(8px)';c.beginPath();c.ellipse(x,y,rx,ry,0,0,Math.PI*2);c.fill();c.filter='none';c.restore();}
  function hoodiePath(x,y,w,h){const p=new Path2D(),b=x+w*.24,by=y+h*.2,bw=w*.52,bh=h*.72;p.moveTo(b+bw*.14,by);p.quadraticCurveTo(b,by+h*.03,b-w*.04,by+h*.12);p.lineTo(x+w*.02,y+h*.52);p.quadraticCurveTo(x,y+h*.62,x+w*.07,y+h*.65);p.lineTo(b+w*.02,y+h*.48);p.lineTo(b+w*.04,by+bh);p.quadraticCurveTo(x+w*.5,y+h*.98,b+bw-w*.04,by+bh);p.lineTo(b+bw-w*.02,y+h*.48);p.lineTo(x+w*.93,y+h*.65);p.quadraticCurveTo(x+w,y+h*.62,x+w*.98,y+h*.52);p.lineTo(b+bw+w*.04,by+h*.12);p.quadraticCurveTo(b+bw,by+h*.03,b+bw*.86,by);p.closePath();const hood=new Path2D();hood.moveTo(x+w*.35,y+h*.24);hood.quadraticCurveTo(x+w*.31,y+h*.04,x+w*.5,y+h*.01);hood.quadraticCurveTo(x+w*.69,y+h*.04,x+w*.65,y+h*.24);hood.quadraticCurveTo(x+w*.5,y+h*.32,x+w*.35,y+h*.24);hood.closePath();return{body:p,hood};}
  function hoodie(c,t,cx,cy,sc,v,s){const w=340*sc,h=560*sc,x=cx-w/2,y=cy-h/2,p=hoodiePath(x,y,w,h);sh(c,cx,y+h*.96,w*.45,h*.025);clip(c,p.body,t,{x,y,w,h},150*sc);clip(c,p.hood,t,{x,y,w,h:h*.35},130*sc);c.strokeStyle='#1b1b1b';c.lineWidth=3*sc;c.stroke(p.body);c.stroke(p.hood);c.save();c.strokeStyle='rgba(240,240,240,.32)';c.lineWidth=sc;c.beginPath();c.moveTo(cx,y+h*.23);c.lineTo(cx,y+h*.91);c.stroke();c.restore();if(v==='front'){c.fillStyle='rgba(12,12,12,.25)';rr(c,x+w*.31,y+h*.69,w*.38,h*.16,18*sc);c.fill();}}
  function teePath(x,y,w,h){const p=new Path2D();p.moveTo(x+w*.33,y+h*.08);p.quadraticCurveTo(x+w*.5,y,x+w*.67,y+h*.08);p.lineTo(x+w*.96,y+h*.2);p.lineTo(x+w*.82,y+h*.43);p.lineTo(x+w*.72,y+h*.37);p.lineTo(x+w*.7,y+h*.96);p.lineTo(x+w*.3,y+h*.96);p.lineTo(x+w*.28,y+h*.37);p.lineTo(x+w*.18,y+h*.43);p.lineTo(x+w*.04,y+h*.2);p.closePath();return p;}
  function shirt(c,t,cx,cy,sc,v,s){const w=365*sc,h=520*sc,x=cx-w/2,y=cy-h/2,p=teePath(x,y,w,h);sh(c,cx,y+h*.98,w*.42,h*.025);clip(c,p,t,{x,y,w,h},165*sc);c.strokeStyle='#1b1b1b';c.lineWidth=2.5*sc;c.stroke(p);}
  function beanie(c,t,cx,cy,sc,v,s){const w=280*sc,h=245*sc,x=cx-w/2,y=cy-h/2;sh(c,cx,y+h*.93,w*.42,h*.035);const p=new Path2D();if(v==='slouch'){p.moveTo(x+w*.06,y+h*.65);p.quadraticCurveTo(x+w*.15,y+h*.08,x+w*.55,y+h*.08);p.quadraticCurveTo(x+w*1.05,y+h*.12,x+w*.86,y+h*.67);p.quadraticCurveTo(x+w*.72,y+h*.92,x+w*.22,y+h*.88);}else{p.moveTo(x+w*.08,y+h*.72);p.quadraticCurveTo(x+w*.08,y+h*.12,x+w*.5,y+h*.06);p.quadraticCurveTo(x+w*.92,y+h*.12,x+w*.92,y+h*.72);}p.closePath();clip(c,p,t,{x,y,w,h},120*sc);c.strokeStyle='#171717';c.lineWidth=3*sc;c.stroke(p);c.fillStyle='rgba(10,10,10,.2)';rr(c,x+w*.08,y+h*.62,w*.84,h*.25,8*sc);c.fill();}
  function mask(c,t,cx,cy,sc,v,s){const w=245*sc,h=360*sc,x=cx-w/2,y=cy-h/2;sh(c,cx,y+h*.95,w*.36,h*.025);const p=new Path2D();p.moveTo(cx,y+h*.02);p.bezierCurveTo(x+w*.16,y+h*.04,x+w*.08,y+h*.33,x+w*.18,y+h*.62);p.lineTo(x+w*.08,y+h*.96);p.lineTo(x+w*.92,y+h*.96);p.lineTo(x+w*.82,y+h*.62);p.bezierCurveTo(x+w*.92,y+h*.33,x+w*.84,y+h*.04,cx,y+h*.02);p.closePath();clip(c,p,t,{x,y,w,h},115*sc);c.strokeStyle='#171717';c.lineWidth=2.5*sc;c.stroke(p);c.fillStyle='#0d0d0d';rr(c,x+w*.2,y+h*.29,w*.6,h*.18,18*sc);c.fill();}
  function cargo(c,t,cx,cy,sc,v,s){const w=300*sc,h=610*sc,x=cx-w/2,y=cy-h/2;sh(c,cx,y+h*.98,w*.4,h*.02);const p=new Path2D();p.moveTo(x+w*.16,y+h*.03);p.lineTo(x+w*.84,y+h*.03);p.lineTo(x+w*.79,y+h*.51);p.lineTo(x+w*.7,y+h*.97);p.lineTo(x+w*.49,y+h*.97);p.lineTo(x+w*.5,y+h*.53);p.lineTo(x+w*.42,y+h*.97);p.lineTo(x+w*.21,y+h*.97);p.lineTo(x+w*.16,y+h*.5);p.closePath();clip(c,p,t,{x,y,w,h},145*sc);c.strokeStyle='#171717';c.lineWidth=2.5*sc;c.stroke(p);const pockets=v==='side'?[[.58,.31,.3,.2]]:[[.12,.3,.27,.17],[.61,.3,.27,.17],[.18,.53,.22,.13],[.6,.53,.22,.13]];pockets.forEach(q=>{c.fillStyle='rgba(10,10,10,.27)';rr(c,x+w*q[0],y+h*q[1],w*q[2],h*q[3],6*sc);c.fill();});}
  function hat(c,t,cx,cy,sc,v,s){const w=330*sc,h=255*sc,x=cx-w/2,y=cy-h/2;sh(c,cx,y+h*.92,w*.44,h*.035);c.save();if(v==='top'){const p=new Path2D();p.ellipse(cx,cy,w*.36,h*.43,0,0,Math.PI*2);clip(c,p,t,{x,y,w,h},125*sc);c.strokeStyle='#171717';c.lineWidth=2.5*sc;c.stroke(p);c.strokeStyle='rgba(230,230,230,.26)';for(let i=0;i<6;i++){const a=Math.PI*2*i/6;c.beginPath();c.moveTo(cx,cy);c.lineTo(cx+Math.cos(a)*w*.36,cy+Math.sin(a)*h*.43);c.stroke();}c.fillStyle='#111';c.beginPath();c.arc(cx,cy,8*sc,0,Math.PI*2);c.fill();c.restore();return;}const crown=new Path2D();if(v==='side'){crown.moveTo(x+w*.18,y+h*.67);crown.quadraticCurveTo(x+w*.19,y+h*.15,x+w*.52,y+h*.08);crown.quadraticCurveTo(x+w*.82,y+h*.1,x+w*.84,y+h*.68);crown.closePath();clip(c,crown,t,{x,y,w,h},130*sc);c.strokeStyle='#171717';c.lineWidth=2.5*sc;c.stroke(crown);const brim=new Path2D();brim.moveTo(x+w*.18,y+h*.64);brim.quadraticCurveTo(x-w*.02,y+h*.7,x+w*.04,y+h*.82);brim.quadraticCurveTo(x+w*.24,y+h*.84,x+w*.43,y+h*.71);brim.closePath();clip(c,brim,t,{x:x-w*.05,y,w:w*.55,h},120*sc);c.stroke(brim);}else{crown.moveTo(x+w*.12,y+h*.68);crown.quadraticCurveTo(x+w*.13,y+h*.13,cx,y+h*.07);crown.quadraticCurveTo(x+w*.87,y+h*.13,x+w*.88,y+h*.68);crown.closePath();clip(c,crown,t,{x,y,w,h},130*sc);c.strokeStyle='#171717';c.lineWidth=2.5*sc;c.stroke(crown);c.strokeStyle='rgba(230,230,230,.24)';c.beginPath();c.moveTo(cx,y+h*.08);c.lineTo(cx,y+h*.68);c.stroke();if(v==='back'){c.fillStyle='#0b0b0b';rr(c,x+w*.32,y+h*.52,w*.36,h*.22,28*sc);c.fill();c.strokeStyle='#1a1a1a';c.lineWidth=4*sc;c.beginPath();c.moveTo(x+w*.3,y+h*.78);c.lineTo(x+w*.72,y+h*.78);c.stroke();}else{const brim=new Path2D();brim.moveTo(x+w*.18,y+h*.63);brim.quadraticCurveTo(cx,y+h*.68,x+w*.82,y+h*.63);brim.quadraticCurveTo(x+w*.75,y+h*.9,cx,y+h*.92);brim.quadraticCurveTo(x+w*.25,y+h*.9,x+w*.18,y+h*.63);brim.closePath();clip(c,brim,t,{x,y:y+h*.55,w,h:h*.42},125*sc);c.stroke(brim);}}c.fillStyle='#111';c.beginPath();c.arc(cx,y+h*.065,7*sc,0,Math.PI*2);c.fill();c.restore();}
  function product(c,t,type,x,y,sc,v,s){if(type==='hoodie')return hoodie(c,t,x,y,sc,v,s);if(type==='hat')return hat(c,t,x,y,sc,v,s);if(type==='beanie')return beanie(c,t,x,y,sc,v,s);if(type==='cargo')return cargo(c,t,x,y,sc,v,s);if(type==='mask')return mask(c,t,x,y,sc,v,s);return shirt(c,t,x,y,sc,v,s);}
  function macro(c,t,x,y,w,h){c.save();rr(c,x,y,w,h,2);c.clip();fill(c,t,x-w*.15,y-h*.2,w*1.3,h*1.4,Math.min(w,h)*.62);c.globalAlpha=.16;c.strokeStyle='#f5f2e7';for(let i=-h;i<w+h;i+=8){c.beginPath();c.moveTo(x+i,y);c.lineTo(x+i-h,y+h);c.stroke();}c.restore();}
  function board(t,s){const cv=$('mockupCanvas'),c=cv.getContext('2d');cv.width=W;cv.height=H;c.fillStyle='#f3f1ec';c.fillRect(0,0,W,H);if(s.product==='hoodie'||s.product==='shirt'){product(c,t,s.product,300,470,1.08,'front',s);product(c,t,s.product,820,470,1.08,'back',s);}else if(s.product==='hat'){product(c,t,'hat',300,330,1.06,'front',s);product(c,t,'hat',820,330,1.06,'side',s);product(c,t,'hat',300,655,1.06,'back',s);product(c,t,'hat',820,655,1.06,'top',s);}else if(s.product==='beanie'){product(c,t,'beanie',300,330,1.08,'front',s);product(c,t,'beanie',820,330,1.08,'side',s);product(c,t,'beanie',300,655,1.08,'back',s);product(c,t,'beanie',820,655,1.08,'slouch',s);}else if(s.product==='cargo'){product(c,t,'cargo',235,485,.9,'front',s);product(c,t,'cargo',560,485,.9,'back',s);product(c,t,'cargo',885,485,.9,'side',s);}else{product(c,t,'mask',245,470,1.18,'front',s);product(c,t,'mask',560,470,1.18,'side',s);product(c,t,'mask',875,470,1.18,'back',s);}macro(c,t,31,930,510,302);}
  function mkManifest(s){return{schema_version:'1.2',generated_at:new Date().toISOString(),brand:s.brand,collection:s.collection,product:s.product,product_name:s.productName,art_direction_profile:'canonical_launch_capsule_v1',reference_target:FAMILY_TITLE[s.family]||s.family,design:{family:s.family,seed:s.seed,scale:s.scale,density:s.density,distress:s.distress,variation_preset:s.variationPreset,feature_motifs:s.featureMotifs,showcase_source:{enabled:s.useShowcaseSource,region:s.showcaseRegion,strength:s.showcaseStrength,asset:'RAC Textile Generator Showcase'},repeat:'tile',master_export_px:4096},outputs:{reference_board_px:[W,H],production_tile_px:[4096,4096]},production_status:'digital_design_ready',pod_status:'requires provider-specific print-template mapping'};}
  function render(){const s=state();tile=makeTile(1024,s);const p=$('studioPatternCanvas'),x=p.getContext('2d');x.clearRect(0,0,p.width,p.height);x.drawImage(tile,0,0,p.width,p.height);board(tile,s);manifest=mkManifest(s);renderRevision+=1;const cv=$('mockupCanvas');cv.dataset.renderRevision=String(renderRevision);cv.dataset.renderProduct=s.product;cv.dataset.renderFamily=s.family;cv.dataset.renderSeed=String(s.seed);cv.dataset.renderVariation=s.variationPreset;$('studioStatus').textContent=`READY · ${s.family.replaceAll('_',' ').toUpperCase()} · SEED ${s.seed}`;}
  function scheduleRender(){if(renderFrame)cancelAnimationFrame(renderFrame);renderFrame=requestAnimationFrame(()=>{renderFrame=0;render();});}
  function dl(url,name){const a=document.createElement('a');a.download=name;a.href=url;a.click();}
  function exportMockup(){if(!tile)render();dl($('mockupCanvas').toDataURL('image/png'),`rac_${state().product}_${Date.now()}_reference-board.png`);}
  function exportTile(){const s=state();$('studioStatus').textContent='BUILDING 4096 PX PRODUCTION TILE…';requestAnimationFrame(()=>{const t=makeTile(4096,s);dl(t.toDataURL('image/png'),`rac_${s.family}_seed-${s.seed}_4096.png`);$('studioStatus').textContent='READY · 4096 PX TILE EXPORTED';});}
  function exportManifest(){if(!manifest)render();const b=new Blob([JSON.stringify(manifest,null,2)],{type:'application/json'}),a=document.createElement('a');a.download=`rac_${state().product}_${Date.now()}_manifest.json`;a.href=URL.createObjectURL(b);a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  function next(){$('studioSeed').value=(+$('studioSeed').value+37)%1000;sync('studioSeed');render();}
  function updateMotifUI(){document.querySelectorAll('.motif-card[data-motif]').forEach(card=>card.classList.toggle('selected',selectedMotifs.has(card.dataset.motif)));const names=[...selectedMotifs].map(v=>v.replaceAll('_',' ').toUpperCase());$('motifCount').textContent=names.length?String(names.length):'AUTO';$('motifSelection').textContent=names.length?names.join(' + '):'Click motifs above to add/remove stylized features from generated patterns.';}
  function toggleMotif(name){if(selectedMotifs.has(name))selectedMotifs.delete(name);else selectedMotifs.add(name);updateMotifUI();render();}
  function setVariation(name){variationPreset=name;document.querySelectorAll('.variation-card[data-variation]').forEach(card=>card.classList.toggle('selected',card.dataset.variation===name));render();}
  function setMode(nextMode){mode=nextMode;document.querySelectorAll('.mode-tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.mode===mode));if(mode==='batch')next();}
  function init(){
    ['studioSeed','studioScale','studioDensity','studioDistress','showcaseStrength'].forEach(id=>{if($(id)){sync(id);$(id).addEventListener('input',()=>{sync(id);scheduleRender();});}});
    $('productType').addEventListener('change',()=>{defaults();render();});
    $('designFamily').addEventListener('change',()=>{defaults();render();});
    ['brandName','productName','collectionName'].forEach(id=>{if($(id))$(id).addEventListener('input',()=>{if(id==='productName')$('productName').dataset.edited='true';scheduleRender();});});
    document.querySelectorAll('.motif-card[data-motif]').forEach(card=>card.addEventListener('click',()=>toggleMotif(card.dataset.motif)));
    document.querySelectorAll('.mode-tab').forEach(tab=>tab.addEventListener('click',()=>setMode(tab.dataset.mode)));
    document.querySelectorAll('.variation-card[data-variation]').forEach(card=>card.addEventListener('click',()=>setVariation(card.dataset.variation)));
    if($('useShowcaseSource'))$('useShowcaseSource').addEventListener('change',render);
    if($('showcaseRegion'))$('showcaseRegion').addEventListener('change',render);
    if($('showcaseReference')&&window.RAC_SHOWCASE_DATA_URI){$('showcaseReference').src=window.RAC_SHOWCASE_DATA_URI;showcaseImage.onload=()=>{showcaseReady=true;render();};showcaseImage.onerror=()=>{$('studioStatus').textContent='SHOWCASE SOURCE ERROR · PROCEDURAL GENERATION STILL AVAILABLE';};showcaseImage.src=window.RAC_SHOWCASE_DATA_URI;}
    updateMotifUI();defaults(true);render();
  }
  return{init,renderAll:render,exportMockup,exportTile,exportManifest,nextVariation:next,toggleMotif,setMode,setVariation,getRenderRevision:()=>renderRevision};
})();
window.addEventListener('DOMContentLoaded',RACStudio.init);