"""Tests for the deterministic stale-artifact detector (drift watch).

Two tiers:

* seeded staleness — each surface check is pointed at a minimal fixture
  tree (or a monkeypatched builder) carrying deliberate drift, and must
  report STALE with a regeneration instruction;
* repo-level — the current repository HEAD must be fully FRESH (the tool
  detects only; nothing is regenerated by these tests).
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from ruthless_pipeline.certification import stale_artifacts as sa  # noqa: E402


# --- fixture helpers ----------------------------------------------------------


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _make_schema_tree(root: Path, schemas: dict[str, dict]) -> None:
    for name, payload in schemas.items():
        _write(root / "schemas" / name, json.dumps(payload))


def _inventory_payload(evidence: list[str] | None = None) -> dict:
    return {
        "inventory_id": "fixture",
        "repo": "ninja-ops-guy/adversarial-clothing-pipeline",
        "classes": sorted(sa.INVENTORY_KNOWN_CLASSES),
        "physical_efficacy_claimed": False,
        "scientific_state": {
            "D2-0005": {"armed": False, "ready_to_arm": False}
        },
        "requirements": [
            {
                "id": "1",
                "class": "PARTIAL",
                "evidence": evidence or [],
            }
        ],
    }


# --- schemas -------------------------------------------------------------------


def test_schemas_fresh(tmp_path):
    _make_schema_tree(tmp_path, {"a.schema.json": {"$id": "a"}, "b.schema.json": {"title": "b"}})
    report = sa.check_schemas_registry(tmp_path)
    assert report.status == sa.STATUS_FRESH


def test_schemas_seeded_invalid_json(tmp_path):
    _write(tmp_path / "schemas" / "broken.schema.json", "{not json")
    report = sa.check_schemas_registry(tmp_path)
    assert report.status == sa.STATUS_STALE
    assert any("invalid JSON" in f for f in report.findings)
    assert report.regenerate


def test_schemas_seeded_duplicate_identifier(tmp_path):
    _make_schema_tree(
        tmp_path,
        {"a.schema.json": {"$id": "dup"}, "b.schema.json": {"$id": "dup"}},
    )
    report = sa.check_schemas_registry(tmp_path)
    assert report.status == sa.STATUS_STALE
    assert any("duplicate schema identifier" in f for f in report.findings)


def test_schemas_seeded_missing_identifier(tmp_path):
    _make_schema_tree(tmp_path, {"a.schema.json": {"fields": {}}})
    report = sa.check_schemas_registry(tmp_path)
    assert report.status == sa.STATUS_STALE
    assert any("no stable identifier" in f for f in report.findings)


def test_schemas_missing_dir(tmp_path):
    report = sa.check_schemas_registry(tmp_path)
    assert report.status == sa.STATUS_MISSING


# --- inventory -------------------------------------------------------------------


def test_inventory_fresh(tmp_path):
    _write(tmp_path / "docs" / "X.md", "x")
    _write(
        tmp_path / sa.INVENTORY_PATH,
        json.dumps(_inventory_payload(["docs/X.md"])),
    )
    report = sa.check_inventory(tmp_path)
    assert report.status == sa.STATUS_FRESH


def test_inventory_seeded_missing_evidence_path(tmp_path):
    _write(
        tmp_path / sa.INVENTORY_PATH,
        json.dumps(_inventory_payload(["docs/DOES_NOT_EXIST.md"])),
    )
    report = sa.check_inventory(tmp_path)
    assert report.status == sa.STATUS_STALE
    assert any("evidence path missing" in f for f in report.findings)


def test_inventory_seeded_safety_flag_drift(tmp_path):
    payload = _inventory_payload()
    payload["physical_efficacy_claimed"] = True
    _write(tmp_path / sa.INVENTORY_PATH, json.dumps(payload))
    report = sa.check_inventory(tmp_path)
    assert report.status == sa.STATUS_STALE
    assert any("physical_efficacy_claimed" in f for f in report.findings)


def test_inventory_seeded_d20005_armed_drift(tmp_path):
    payload = _inventory_payload()
    payload["scientific_state"]["D2-0005"]["armed"] = True
    _write(tmp_path / sa.INVENTORY_PATH, json.dumps(payload))
    report = sa.check_inventory(tmp_path)
    assert report.status == sa.STATUS_STALE
    assert any("D2-0005 arming" in f for f in report.findings)


def test_inventory_missing(tmp_path):
    assert sa.check_inventory(tmp_path).status == sa.STATUS_MISSING


# --- manuscript figures / exports -----------------------------------------------


def test_manuscript_pins_fresh(tmp_path):
    source = b"payload"
    _write(tmp_path / "manuscript" / "evidence" / "src.json", "")
    (tmp_path / "manuscript" / "evidence" / "src.json").write_bytes(source)
    digest = hashlib.sha256(source).hexdigest()
    scaffold = {
        "figure_id": "F1",
        "data": [
            {"source_artifacts": {"manuscript/evidence/src.json": digest}}
        ],
    }
    _write(tmp_path / "manuscript" / "figures" / "F1.json", json.dumps(scaffold))
    report = sa._check_manuscript_dir(tmp_path, "manuscript/figures")
    assert report.status == sa.STATUS_FRESH


def test_manuscript_pins_seeded_hash_drift(tmp_path):
    _write(tmp_path / "manuscript" / "evidence" / "src.json", "changed bytes")
    scaffold = {
        "data": [
            {
                "source_artifacts": {
                    "manuscript/evidence/src.json": "0" * 64,
                }
            }
        ]
    }
    _write(tmp_path / "manuscript" / "exports" / "m.json", json.dumps(scaffold))
    report = sa._check_manuscript_dir(tmp_path, "manuscript/exports")
    assert report.status == sa.STATUS_STALE
    assert any("source hash drift" in f for f in report.findings)


def test_manuscript_pins_seeded_missing_source(tmp_path):
    scaffold = {"data": [{"path": "manuscript/evidence/gone.json", "sha256": "0" * 64}]}
    _write(tmp_path / "manuscript" / "figures" / "F1.json", json.dumps(scaffold))
    report = sa._check_manuscript_dir(tmp_path, "manuscript/figures")
    assert report.status == sa.STATUS_STALE
    assert any("is missing" in f for f in report.findings)


# --- cluster results hash pin -----------------------------------------------------


def test_cluster_pin_fresh(tmp_path):
    content = b"frozen simulation output"
    path = tmp_path / sa.CLUSTER_RESULTS_PATH
    path.parent.mkdir(parents=True)
    path.write_bytes(content)
    report = sa.check_cluster_results_pin(
        tmp_path, expected_sha256=hashlib.sha256(content).hexdigest()
    )
    assert report.status == sa.STATUS_FRESH


def test_cluster_pin_seeded_mismatch(tmp_path):
    path = tmp_path / sa.CLUSTER_RESULTS_PATH
    path.parent.mkdir(parents=True)
    path.write_bytes(b"tampered")
    report = sa.check_cluster_results_pin(tmp_path, expected_sha256="0" * 64)
    assert report.status == sa.STATUS_STALE
    assert any("hash pin mismatch" in f for f in report.findings)
    # detect-only: the checker must not rewrite the artifact
    assert path.read_bytes() == b"tampered"


# --- provenance graph / dashboard (builder-level seeding) -------------------------


def test_provenance_graph_seeded_drift(monkeypatch):
    original = sa.build_graph

    def drifted(root):
        graph = original(root)
        graph["nodes"] = graph["nodes"] + [
            {"id": "injected", "path": "injected", "sha256": "0" * 64}
        ]
        return graph

    monkeypatch.setattr(sa, "build_graph", drifted)
    report = sa.check_provenance_graph(REPO_ROOT)
    assert report.status == sa.STATUS_STALE
    assert report.regenerate


def test_dashboard_seeded_drift(monkeypatch):
    from scripts import export_dashboard_data

    original = export_dashboard_data.build_dashboard

    def drifted(root):
        payload = original(root)
        payload["records"].append({"experiment_id": "INJECTED"})
        return payload

    monkeypatch.setattr(export_dashboard_data, "build_dashboard", drifted)
    report = sa.check_dashboard(REPO_ROOT)
    assert report.status == sa.STATUS_STALE
    assert "PYTHONPATH=. python scripts/export_dashboard_data.py" in report.regenerate


# --- report aggregation -----------------------------------------------------------


def test_report_is_machine_readable_and_deterministic():
    report = sa.check_repo(REPO_ROOT)
    payload = report.to_dict()
    assert payload["schema_version"] == "1.0"
    assert payload["generator"] == "scripts/check_stale_artifacts.py"
    surfaces = {s["surface"]: s["status"] for s in payload["surfaces"]}
    assert set(surfaces) == {
        sa.PROVENANCE_GRAPH_PATH,
        sa.SCHEMAS_DIR,
        sa.INVENTORY_PATH,
        sa.MANUSCRIPT_FIGURES_DIR,
        sa.MANUSCRIPT_EXPORTS_DIR,
        sa.DASHBOARD_PATH,
        sa.CLUSTER_RESULTS_PATH,
        "docs/** + manuscript/backlog/**",
    }
    # The documentation surface reuses doc_lint, which has its own dedicated
    # repo-cleanliness test (test_doc_lint.py::test_current_repo_lints_clean);
    # cross-swarm doc drift is reported there. Here we pin the surfaces this
    # tool uniquely owns.
    artifact_surfaces = {
        k: v for k, v in surfaces.items() if k != "docs/** + manuscript/backlog/**"
    }
    assert all(status == sa.STATUS_FRESH for status in artifact_surfaces.values())
    assert payload["stale"] == any(
        status != sa.STATUS_FRESH for status in surfaces.values()
    )


def test_current_repo_artifact_surfaces_fresh_via_cli():
    proc = subprocess.run(
        [sys.executable, "scripts/check_stale_artifacts.py"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    payload = json.loads(proc.stdout)
    # Exit code mirrors the aggregate stale flag (0 or 1).
    assert proc.returncode == (1 if payload["stale"] else 0)
    for surface in payload["surfaces"]:
        if surface["surface"] == "docs/** + manuscript/backlog/**":
            continue  # owned by test_doc_lint.py's repo-cleanliness test
        assert surface["status"] == sa.STATUS_FRESH, surface["findings"]


def test_cli_exit_nonzero_on_staleness(tmp_path):
    _write(tmp_path / "schemas" / "broken.schema.json", "{nope")
    proc = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "check_stale_artifacts.py"),
            "--repo-root",
            str(tmp_path),
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 1
    payload = json.loads(proc.stdout)
    assert payload["stale"] is True
    statuses = {s["surface"]: s["status"] for s in payload["surfaces"]}
    assert statuses[sa.SCHEMAS_DIR] == sa.STATUS_STALE
